name: CI dev-base ADE image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: ./hooks/build.sh dev-base

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

